### ISSUE TITLE
Dockerize the app into two containers

### ISSUE THREAD

**Issue by mycrazyfish** [mycrazyfish/nodesql#10]
- backend container

- frontend container

- frontend container to connect to backend 

- open ports from host only to frontend

- document in Readme.MD the deployment process.

**Comment by mycrazyfish** [comment]
welcome the idea of kubernetes and swarm at the same time. can take multiple PRs based on effort

**Comment by taylor009** [comment]
@mycrazyfish  I can work on this. could you please assign it to me.
