### ISSUE TITLE
Initialise a Basic Node API 

### ISSUE THREAD

**Issue by arpanchhetri** [mycrazyfish/nodesql#4]
Use expess to start a new app on a high port.

**Comment by lilcoltsmith** [comment]
I would like to work on this. Could you assign it to me?

**Comment by mycrazyfish** [comment]
sure, but maybe we need to get #3 in first? so that we know how we are going to keep the backend and frontend separate

**Comment by lilcoltsmith** [comment]
@mycrazyfish , if you would like, you can assign #3  to me as well? I can just setup a demo angular app and a basic express app.

**Comment by mycrazyfish** [comment]
awesome!
