### ISSUE TITLE
Create Readme for API and Repository

### ISSUE THREAD

**Issue by mycrazyfish** [mycrazyfish/nodesql#8]
- Create a Readme.MD in api/
- Copy the contents of main Readme.md into api/Readme.MD.
- Tidy up api/Readme.MD according to node best practices.
- Give your best shot at creating a brand new main Readme.MDs for the repo

**Comment by abhishekpatel946** [comment]
Hey @mycrazyfish, 
I'm working on it to create an awesome **_README.md_**

**Comment by mycrazyfish** [comment]
@abhishekpatel946 

You could create individual PRs for each Readme.MD if you like, and link them to this issue. 

Cheers for your help though.

**Comment by abhishekpatel946** [comment]
> @abhishekpatel946
> 
> You could create individual PRs for each Readme.MD if you like, and link them to this issue.
> 
> Cheers for your help though.

@mycrazyfish 
Okay, I created an individual branch and working. Then I create a PRs for each Readme.md

**Comment by PravunathSingh** [comment]
Hey, @abhishekpatel946 I would like to work on creating new README.md for the repo. Would you please assign this issue to me

**Comment by mycrazyfish** [comment]
@PravunathSingh you could take over the repo md. thanks for your contib
